// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-T9v2UDqQGmpIsp0xl7UmICYa0udAeE',
    appId: '1:634529382291:web:ce046e6d635e5285f23266',
    messagingSenderId: '634529382291',
    projectId: 'mediconnect-ffff6',
    authDomain: 'mediconnect-ffff6.firebaseapp.com',
    storageBucket: 'mediconnect-ffff6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZpt66BFz53Mks88rcmwNz5MlYZD6RxE',
    appId: '1:634529382291:android:c527e706aedd185ff23266',
    messagingSenderId: '634529382291',
    projectId: 'mediconnect-ffff6',
    storageBucket: 'mediconnect-ffff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmsf_QO0-F0tGgz506tsQe6953wD16LkU',
    appId: '1:634529382291:ios:092fb0ca4a9ad190f23266',
    messagingSenderId: '634529382291',
    projectId: 'mediconnect-ffff6',
    storageBucket: 'mediconnect-ffff6.firebasestorage.app',
    iosBundleId: 'com.mediconnect.mediconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmsf_QO0-F0tGgz506tsQe6953wD16LkU',
    appId: '1:634529382291:ios:092fb0ca4a9ad190f23266',
    messagingSenderId: '634529382291',
    projectId: 'mediconnect-ffff6',
    storageBucket: 'mediconnect-ffff6.firebasestorage.app',
    iosBundleId: 'com.mediconnect.mediconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo-T9v2UDqQGmpIsp0xl7UmICYa0udAeE',
    appId: '1:634529382291:web:b2cbfddf607ab30af23266',
    messagingSenderId: '634529382291',
    projectId: 'mediconnect-ffff6',
    authDomain: 'mediconnect-ffff6.firebaseapp.com',
    storageBucket: 'mediconnect-ffff6.firebasestorage.app',
  );
}
